"""
Django settings for school_saas project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Load .env file if it exists
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--xujvej22!o+9(65*p_n9!o$uw1ofc*(=+)&9=mw_7i2-q*^^v'

# SECURITY WARNING: don't run with debug turned on in production!
_IS_CLOUD = bool(
    os.getenv("RAILWAY_ENVIRONMENT")
    or os.getenv("RAILWAY_SERVICE_NAME")
    or os.getenv("RENDER")
    or os.getenv("FLY_APP_NAME")
)
DEBUG = os.getenv("DEBUG", "False" if _IS_CLOUD else "True") == "True"

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
BASE_DOMAIN = os.getenv('BASE_DOMAIN', 'localhost')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Local apps
    'users',
    'schools',
    'students',
    'teachers',
    'attendance',
    'fees',
    'core',
    'exams',
    'notices',
    'timetable',
    'assignments',
    'classes',
    'library',
    'transport',
    'staff',
    'inventory',
    'chat',
]

# Groq AI Settings
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.PlatformAccessMiddleware',
    'core.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'school_saas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_saas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Prefer Railway's full DATABASE_URL reference. Only build from PG* when
# DATABASE_URL is missing — a hand-typed PGPASSWORD (e.g. local hamza123)
# must never override the linked Postgres URL.

_LOCAL_DB_URL = "postgres://postgres:hamza123@127.0.0.1:5432/school_db"


def _build_database_url():
    from urllib.parse import quote_plus

    explicit = (
        os.getenv("DATABASE_URL")
        or os.getenv("DATABASE_PRIVATE_URL")
        or os.getenv("POSTGRES_URL")
    )
    if explicit:
        return explicit.strip().strip('"').strip("'")

    pg_host = os.getenv("PGHOST")
    pg_user = os.getenv("PGUSER")
    pg_password = os.getenv("PGPASSWORD")
    pg_db = os.getenv("PGDATABASE")
    pg_port = os.getenv("PGPORT") or "5432"
    if pg_host and pg_user and pg_password and pg_db:
        return (
            f"postgres://{quote_plus(pg_user)}:{quote_plus(pg_password)}"
            f"@{pg_host}:{pg_port}/{pg_db}"
        )
    return None


_DATABASE_URL = _build_database_url()
_DB_SOURCE = "DATABASE_URL" if (
    os.getenv("DATABASE_URL") or os.getenv("DATABASE_PRIVATE_URL") or os.getenv("POSTGRES_URL")
) else ("PG*" if _DATABASE_URL else "none")

if not _DATABASE_URL:
    if DEBUG:
        _DATABASE_URL = _LOCAL_DB_URL
        _DB_SOURCE = "local-default"
    else:
        raise RuntimeError(
            "DATABASE_URL is not set. On Railway web service → Variables: "
            "delete any hand-typed DATABASE_URL/PGPASSWORD, then Add Variable → "
            "Add Reference → Postgres.DATABASE_URL"
        )

_is_railway_internal = "railway.internal" in _DATABASE_URL
_ssl_require = (
    os.getenv("DB_SSL_REQUIRE", "").lower() in {"1", "true", "yes"}
    or (
        not DEBUG
        and not _is_railway_internal
        and "127.0.0.1" not in _DATABASE_URL
        and "localhost" not in _DATABASE_URL
    )
)

DATABASES = {
    "default": dj_database_url.parse(
        _DATABASE_URL,
        conn_max_age=0,
        ssl_require=_ssl_require,
    )
}

_db_host = (DATABASES["default"].get("HOST") or "").strip()
_db_user = (DATABASES["default"].get("USER") or "").strip()
_db_name = (DATABASES["default"].get("NAME") or "").strip()
_db_password = DATABASES["default"].get("PASSWORD") or ""

if os.getenv("RAILWAY_ENVIRONMENT") or os.getenv("RAILWAY_SERVICE_NAME"):
    print(
        f"[db] source={_DB_SOURCE} host={_db_host!r} user={_db_user!r} "
        f"name={_db_name!r} password_len={len(_db_password)} "
        f"ssl_require={_ssl_require}",
        flush=True,
    )

if not DEBUG and _db_host in {"127.0.0.1", "localhost"}:
    raise RuntimeError(
        f"DATABASE_URL points to {_db_host}, which is unavailable in production. "
        "Use your cloud Postgres URL instead (Railway Postgres plugin / Neon / etc)."
    )

# Catch the common local-password paste mistake early with a clear message.
if (
    (os.getenv("RAILWAY_ENVIRONMENT") or os.getenv("RAILWAY_SERVICE_NAME"))
    and _db_password in {"hamza123", "postgres", "password", "root", ""}
):
    raise RuntimeError(
        "Railway is using an invalid/local Postgres password "
        f"(source={_DB_SOURCE}, user={_db_user!r}). "
        "In the web service Variables: delete DATABASE_URL, PGPASSWORD, PGUSER, "
        "PGHOST, PGDATABASE if they were typed manually, then re-add them as "
        "Variable References from your Postgres service (Postgres.DATABASE_URL)."
    )

# Future: Tenant databases will be injected dynamically at runtime
# This placeholder allows the framework to be multi-db aware without changing current behavior.
TENANT_DATABASES = {
    'example': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'example_db',
    }
}
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]
DATABASE_ROUTERS = [
    'core.db_router.TenantDatabaseRouter'
]

# SaaS Architecture Control Flags
# Shared-schema tenancy (school FK) is the default. Dedicated DBs are opt-in.
ENABLE_TENANT_DB_CREATION = os.getenv('ENABLE_TENANT_DB_CREATION', 'False') == 'True'
TENANT_DB_SWITCHING_ENABLED = os.getenv('TENANT_DB_SWITCHING_ENABLED', 'False') == 'True' 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'UPDATE_LAST_LOGIN': True,
}

# CORS & CSRF
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:5175,http://127.0.0.1:5175,https://multi-tenant-production-6364.up.railway.app').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:5175,http://127.0.0.1:5175,https://multi-tenant-production-6364.up.railway.app').split(',')
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-tenant-domain',
]

# SaaS Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'tenant_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'tenant_audit.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'tenant': {
            'handlers': ['console', 'tenant_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
