# Generated by Django 6.0.4 on 2026-05-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_database_name'),
        ('teachers', '0002_teacher_classes_teacher_email_teacher_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
