# Generated by Django 6.0.4 on 2026-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='plan_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='plan_status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Active', 'Active')], default='Inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='plan_type',
            field=models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Business', 'Business'), ('Pro', 'Pro')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
