# Generated by Django 6.0.4 on 2026-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_plan_amount_school_plan_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='is_landing_page_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#1e3a8a', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
