# Generated by Django 6.0.4 on 2026-04-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_about_text_school_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='school',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_landing_page_active',
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='school',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='school',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
    ]
