# Generated by Django 6.0.4 on 2026-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_about_text_remove_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
