# Generated by Django 6.0.4 on 2026-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_landing_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='landing_show_stats',
            field=models.BooleanField(default=True),
        ),
    ]
