# Generated by Django 6.0.4 on 2026-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_landing_show_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='landing_hero_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
