# Generated by Django 6.0.4 on 2026-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_landing_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='landing_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='landing_testimonials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
