# Generated by Django 6.0.4 on 2026-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_school_landing_features_school_landing_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='landing_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='landing_programs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
