# Generated by Django 6.0.4 on 2026-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_landing_languages_school_landing_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='landing_center_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
