# Generated by Django 6.0.4 on 2026-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='database_name',
            field=models.CharField(blank=True, help_text='Name of the dedicated database for this school', max_length=100, null=True),
        ),
    ]
