# Generated by Django 6.0.4 on 2026-05-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text="Groq API Key for this school's AI Assistant", max_length=255, null=True),
        ),
    ]
