# Generated by Django 6.0.4 on 2026-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_ai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dashboard_accent_color',
            field=models.CharField(default='#10b981', help_text='Accent color for buttons/highlights', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='dashboard_primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary color for admin dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='dashboard_secondary_color',
            field=models.CharField(default='#1e293b', help_text='Sidebar/Background color for dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='school_favicons/'),
        ),
        migrations.AddField(
            model_name='school',
            name='landing_secondary_color',
            field=models.CharField(default='#1e40af', help_text='Secondary color for landing page', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='landing_primary_color',
            field=models.CharField(default='#3b82f6', help_text='Primary color for landing page (e.g. #3b82f6)', max_length=20),
        ),
    ]
