# Generated by Django 5.2.16 on 2026-08-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_dashboard_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='bform_cnic',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_applying',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='father_cnic',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mother_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='previous_school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='dashboard_accent_color',
            field=models.CharField(default='#FF8C42', help_text='Accent color for buttons/highlights', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='dashboard_primary_color',
            field=models.CharField(default='#F15A24', help_text='Primary color for admin dashboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='dashboard_secondary_color',
            field=models.CharField(default='#0F172A', help_text='Sidebar/Background color for dashboard', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='landing_primary_color',
            field=models.CharField(default='#e8b86d', help_text='Accent/gold color for landing page', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='landing_secondary_color',
            field=models.CharField(default='#08131c', help_text='Deep ink color for landing page', max_length=20),
        ),
    ]
