# Generated by Django 5.2.16 on 2026-08-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_alter_schoolclass_shift"),
        ("schools", "0019_school_landing_copy"),
        ("teachers", "0005_teacher_login_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="assigned_incharge",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_reviews",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="incharge_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="classes.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="test_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="test_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="test_total",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending class review"),
                    ("PendingIncharge", "Pending class test"),
                    ("PendingAdmin", "Pending admin approval"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="PendingIncharge",
                max_length=20,
            ),
        ),
    ]
