# Generated by Django 5.2.16 on 2026-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_board_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('All', 'Everyone'), ('Students', 'Students'), ('Teachers', 'Teachers'), ('Parents', 'Parents'), ('Class', 'Specific class')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Holiday', 'Holiday'), ('Exam', 'Exam'), ('Fee', 'Fee'), ('Event', 'Event'), ('Emergency', 'Emergency')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
    ]
