# Generated by Django 5.2.16 on 2026-08-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_timetable_period_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Break', 'Break'), ('Assembly', 'Assembly'), ('Sports', 'Sports')], default='Lecture', max_length=20),
        ),
    ]
