# Generated by Django 5.2.16 on 2026-08-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0005_teacher_login_user"),
        ("timetable", "0004_period_type_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodCover",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_by", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cover_teacher",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_covers",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covers",
                        to="timetable.timetable",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "period_id"],
                "unique_together": {("period", "date")},
            },
        ),
    ]
