# Generated by Django 6.0.4 on 2026-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
