# Generated by Django 5.2.16 on 2026-08-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_schedule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
    ]
