# Generated by Django 6.0.4 on 2026-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0003_alter_student_options_alter_student_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('school', 'student', 'date')},
        ),
    ]
