# Generated by Django 5.2.16 on 2026-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_fee_choices_and_paid_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
