# Generated by Django 5.2.16 on 2026-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("accountant", "Accountant"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                max_length=20,
            ),
        ),
    ]
