# Generated by Django 6.0.4 on 2026-04-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schools', '0002_school_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
