# Generated by Django 6.0.4 on 2026-05-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='System Configuration', max_length=100)),
                ('groq_api_key', models.CharField(blank=True, help_text='Global Groq API Key for AI Assistant', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
