# Generated by Django 5.2.16 on 2026-08-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_globalsetting"),
        ("teachers", "0005_teacher_login_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[("All", "Everyone"), ("Admin", "School admin"), ("Teacher", "Teacher")],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="link_path",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="notification",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="teachers.teacher",
            ),
        ),
    ]
