# Generated by Django 5.2.16 on 2026-08-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remap_audience(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    Notification.objects.filter(school__isnull=False, teacher__isnull=False).update(audience="Teacher")
    Notification.objects.filter(school__isnull=False, teacher__isnull=True, audience__in=["All", ""]).update(
        audience="Admin"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_notification_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[
                    ("Admin", "School admin"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Accountant", "Accountant"),
                    ("Student", "Student"),
                    ("All", "Everyone"),
                ],
                default="Admin",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="core.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("notification", "user")},
            },
        ),
        migrations.RunPython(code=remap_audience, reverse_code=migrations.RunPython.noop),
    ]
